LOGIN

	SELECT nome
	FROM USUARIO u
	WHERE u.ID_usuario = @
	AND u.senha = %

LISTAR HORÁRIOS 
	
	FILTRANDO POR MÉDICO
	
		SELECT * FROM AGENDAMENTO a
			INNER JOIN MEDICO m
			ON m.ID_USUARIO = a.ID_MEDICO
			INNER JOIN LUGAR l
			on l.
		WHERE a.ID_MEDICO = @ID_MEDICO
		
	FILTRANDO POR LOCAL
	
DISPONIBILIZAR HORÁRIO - status 0 de criado

	INSERT INTO AGENDAMENTO VALUES 
	(0,@ID_MEDICO,@CADASTRO,@DATA_HORA_INICIO,@DATA_HORA_FIM,0,@VOUCHER,@ID_PACIENTE,@VALOR) 


	
LISTAR AGENDAMENTOS DE UM PACIENTE

	SELECT * FROM AGENDAMENTO
	WHERE ID_PACIENTE = @ID_PACIENTE
	ORDER BY IN_STATUS ASC
	
AGENDAR UM HORARIO - status 1 de agendado

	UPDATE AGENDAMENTO
	SET IN_STATUS=1, ID_PACIENTE=@ID_PACIENTE, VOUCHER = @VOUCHER
	WHERE ID_AGENDAMENTO = @ID_AGENDAMENTO
	
CANCELAR AGENDAMENTO - status 2 de cancelado

	UPDATE AGENDAMENTO
	SET IN_STATUS=-1
	WHERE ID_AGENDAMENTO=@ID_AGENDAMENTO
	


